exclude.urls[0]=/passport/getSMSCode
exclude.urls[1]=/passport/login
exclude.urls[2]=/passport/logout
exclude.urls[3]=/saas/getQRToken
exclude.urls[4]=/saas/scanCode
exclude.urls[5]=/saas/codeHasBeenRead
exclude.urls[6]=/saas/goQRLogin
exclude.urls[7]=/saas/checkLogin
exclude.urls[8]=/saas/info
exclude.urls[9]=/saas/logout
exclude.urls[10]=/admin/login
exclude.urls[11]=/admin/logout
exclude.urls[12]=/w/port
exclude.urls[13]=/dataDict/app/getItemsByKeys
exclude.urls[14]=/dataDict/app/getItemsByKeys2
exclude.urls[15]=/company/modify
exclude.urls[16]=/company/fairLock
exclude.urls[17]=/company/readLock
exclude.urls[18]=/company/writeLock
exclude.urls[19]=/company/semaphore/lock
exclude.urls[20]=/company/semaphore/release
exclude.urls[21]=/company/release/car
exclude.urls[22]=/company/doneStep/car
exclude.urls[23]=/resume/refresh
exclude.urls[24]=/tradeOrder/notifyMerchantOrderPaid

exclude.ipLimitUrls[0]=/saas/getQRToken

exclude.fileStart=/static/**